name: Deploy Azure Hub-Spoke Network

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RESOURCE_GROUP: 'hub-rg'

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Deploy Hub VNet
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/hub-vnet.bicep'
        deploymentName: 'hub-vnet-deployment'
        failOnStdErr: false
        
    - name: Deploy Spoke 1 VNet  
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/spoke1-vnet.bicep'
        deploymentName: 'spoke1-vnet-deployment'
        failOnStdErr: false
        
    - name: Deploy Spoke 2 VNet
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/spoke2-vnet.bicep'
        deploymentName: 'spoke2-vnet-deployment'
        failOnStdErr: false
        
    - name: Configure VNet Peering
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/vnet-peering.bicep'
        deploymentName: 'vnet-peering-deployment'
        failOnStdErr: false
        
    - name: Deploy VPN Gateway
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/vpn-gateway.bicep'
        deploymentName: 'vpn-gateway-deployment'
        failOnStdErr: false
        
    - name: Configure Azure Bastion
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/bastion.bicep'
        deploymentName: 'bastion-deployment'
        failOnStdErr: false
        
    - name: Apply Network Security Groups
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/nsg.bicep'
        deploymentName: 'nsg-deployment'
        failOnStdErr: false
        
    - name: Tag Resources
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: './bicep/resource-tags.bicep'
        deploymentName: 'resource-tags-deployment'
        failOnStdErr: false
