name: Deploy Azure Hub-Spoke Network

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy Hub VNet
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'hub-rg'
        template: 'hub-vnet.bicep'
        
    - name: Deploy Spoke 1 VNet  
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'spoke1-rg'
        template: 'spoke1-vnet.bicep'
        
    - name: Deploy Spoke 2 VNet
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'spoke2-rg'
        template: 'spoke2-vnet.bicep'
        
    - name: Configure VNet Peering
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'hub-rg'
        template: 'vnet-peering.bicep'
        
    - name: Deploy VPN Gateway
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'hub-rg'
        template: 'vpn-gateway.bicep'
        
    - name: Configure Azure Bastion
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'hub-rg'
        template: 'bastion.bicep'
        
    - name: Apply Network Security Groups
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'hub-rg'
        template: 'nsg.bicep'
        
    - name: Tag Resources
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: 'hub-rg'
        template: 'resource-tags.bicep'
